### ISSUE TITLE
SofaRun 6.1 Device Type ESE SCC instead of OCM

### ISSUE THREAD

**Issue by Vampier** [MiSTer-devel/MSX_MiSTer#20]
First of all excellent work on the KdL port for the OCM (ESE) Mister core. As an long time MSX user I really appreciate the work that is being put into keeping the platform alive. 

Not a big deal but SofaRun 6.1 has been made for the latest version of the KdL version. I talked to Louthrax about having to pick the ESE SCC flash device to get most smaller ROMs working and he said that a new mapper was implemented for the OCM. 

His exact words "If I remember correctly I used a new mapper function in the latest SofaRun release, but this mapper function is only available on recent OCM firmwares. Have you tried the latest KDL version ?"

As I said not a big deal as I can work around this but it would be nice to have the core synced up with the last changes.

Looking forward to the next release - if you need a tester let me know - I have experience in testing for openMSX and C-BIOS.

**Comment by MP2E** [comment]
Looks like sorgelig updated the MSX core to the newest OCM changes! Does this address this issue?

Thanks sorgelig :)

**Comment by sorgelig** [comment]
i have almost no experience with MSX. But according that info all you need is to update the MSX BIOS to latest.

**Comment by Vampier** [comment]
Thanks, I already have the latest version from KdL - the SofaRun author might purchase a MiSTer really soon. I personally think it might have to do with a slot issue (internal slot layout) which is out of scope for this issue. I will talk to Louthtrax/KdL/Nyrikki about this again and see if we can something do make it easier. (it has to do with a linear mapper that was implemented/introduced in 3.8)
