### ISSUE TITLE
Feature Request: Add more keyboard input mapping options to joystick.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/MSX_MiSTer#24]
Edit: Someone said you could remap keyboard to joystick. I will test this out.

For the most part I can get around using the MSX core with just a controller and Sofarun, but there are times where something requires a Space Bar press and it would be nice if I could just map it to my controller.  Also would be nice to add some other inputs like F2, F3, F4 and such that opens up Loading and Saving screens.

**Comment by seascape** [comment]
May I ask if this was really implemented?

I came looking because I realized the two controllers buttons wasn't quite enough for all games, but the core only allows the gamepad to map the two buttons, and not additional keys like F1 or Space.
